### PR TITLE
Add LoopingRiveIcon

### PR DESCRIPTION
**Pull request by ZhuJHua**
Added a new LoopingRiveIcon widget for rendering a standalone, infinitely looping Rive animated icon.

### CODE REVIEW

**Comment by ZhuJHua** [comment]
I apologize for starting directly on the main branch, which has combined the two changes into a single PR. However, I believe this is a minor modification and should not cause significant issues.  If needed, I’m happy to make adjustments or create separate branches for each change.

**Comment by nikkieke** [comment]
> I apologize for starting directly on the main branch, which has combined the two changes into a single PR. However, I believe this is a minor modification and should not cause significant issues. If needed, I’m happy to make adjustments or create separate branches for each change.

it's fine. No need to create a different branch

**Comment by nikkieke** [comment]
I have reviewed your contributions. Thanks again for contributing.
To achieve a looping rive icon, we don't need to create a separate widget. I suggest you wrap the `InkWell` widget with an `AbsorbPointer`, then create a new param `enableAbsorbPointer` for the `RiveAnimatedIcon` widget, this param should be false by default. You can then pass this param to `AbsorbPointer` to enable or disable the `AbsorbPointer`. The icon already loops by default.

**Comment by ZhuJHua** [comment]
I think the current name `RiveAnimatedIcon` is a bit misleading, as it currently feels more like a button than an icon. Distinguishing it, similar to distinguishing between an `IconButton` and an `Icon`, improves clarity. With regard to using `AbsorbPointer`, I think removing unnecessary widgets can make the widget tree more lightweight, although not doing so may not cause serious performance issues.

**Comment by ZhuJHua** [comment]
II recommend having two separate components: the `RiveAnimatedIcon` and the `RiveAnimatedIconButton`. Although this will bring some breaking changes.

**Comment by nikkieke** [comment]
> I think the current name `RiveAnimatedIcon` is a bit misleading, as it currently feels more like a button than an icon. Distinguishing it, similar to distinguishing between an `IconButton` and an `Icon`, improves clarity. With regard to using `AbsorbPointer`, I think removing unnecessary widgets can make the widget tree more lightweight, although not doing so may not cause serious performance issues.

True. It has some button features that make it different from regular icons. However, the intention behind building the RiveAnimatedIcon like this is to have an animated icon that its animation can be controlled by tap or hover instead of just a regular looping animation. It wasn't intended to be a button.
I also understand your proposal for RiveAnimatedIcon and RiveAnimatedIconButton, it is a great idea. Although, as you previously mentioned it will lead to breaking changes.
The issue you raised earlier was that you needed a looping rive animated icon without the inkwell. We can easily achieve this using the absorbPointer.

**Comment by ZhuJHua** [comment]
> > I think the current name `RiveAnimatedIcon` is a bit misleading, as it currently feels more like a button than an icon. Distinguishing it, similar to distinguishing between an `IconButton` and an `Icon`, improves clarity. With regard to using `AbsorbPointer`, I think removing unnecessary widgets can make the widget tree more lightweight, although not doing so may not cause serious performance issues.
> 
> True. It has some button features that make it different from regular icons. However, the intention behind building the RiveAnimatedIcon like this is to have an animated icon that its animation can be controlled by tap or hover instead of just a regular looping animation. It wasn't intended to be a button. I also understand your proposal for RiveAnimatedIcon and RiveAnimatedIconButton, it is a great idea. Although, as you previously mentioned it will lead to breaking changes. The issue you raised earlier was that you needed a looping rive animated icon without the inkwell. We can easily achieve this using the absorbPointer.

Okay. Thanks again!

**Pull request closed without merging**
